### ISSUE TITLE
Parameters on perl have a red background ( no tresitter )

### ISSUE THREAD

**Issue by marcelarie** [mrjones2014/lighthaus.nvim#10]
With the regex highlight the theme shows this red squares as background on the parameters area:

![light](https://user-images.githubusercontent.com/62728887/154272892-915df888-7176-412e-9df0-647a1ee4f1c7.png)

this is how `grubox-flat` handles it:
![2022-02-16_14-21](https://user-images.githubusercontent.com/62728887/154273169-983ad8bd-4c35-48a1-9b3c-1c3675646671.png)

**Comment by mrjones2014** [comment]
Using `:echo synIDattr(synID(line('.'), col('.'), 1), 'name')` to get the name of the highlight under the cursor, it's being highlighted as `perlSubPrototypeError`. Pretty sure this is a bug with the regex-based perl syntax highlighter, not with the theme.

But, after googling a bit, others have reported the same issue:

- https://github.com/vim-perl/vim-perl/issues/260
- https://github.com/dusktreader/dot/blob/master/.vim/after/syntax/perl/workarounds.vim

That said, I'll add the workaround from the 2nd link there.

**Comment by marcelarie** [comment]
thanks!
