### ISSUE TITLE
Add transparency support

### ISSUE THREAD

**Issue by mrjones2014** [mrjones2014/lighthaus.nvim#11]
Currently lighthaus.nvim doesn't support transparency. Would be cool to support it.

**Comment by mrjones2014** [comment]
Good tip, thanks! I can do italic comments too. I'll make this a configuration option, not enabled by default because I don't want to change people's existing setups.

**Comment by tsyroid** [comment]
Yep. Exactly. Do it like sainnhe does. All the fancy stuff defaults to
off. To enable it you have to explicitly set a ‘vim.g’ variable (a list of
available options is buried in the edge help file).

**Comment by mrjones2014** [comment]
@tsyroid done, let me know what you think! Check the readme for how to enable the new options.
