### ISSUE TITLE
`colorcolumn` on top of plain text

### ISSUE THREAD

**Issue by marcelarie** [mrjones2014/lighthaus.nvim#12]
I tried loading the settings before and after the plugin loads with not effect.

![lightbug](https://user-images.githubusercontent.com/62728887/156150768-00be33ba-f147-4e57-a4f7-3954ef68dd12.png)
Here is the same line with visual lne to highlight the missing text:
![lightbug 2](https://user-images.githubusercontent.com/62728887/156150772-6687e4cb-31b6-49f6-8b25-c1e8ea5fed17.png)

My `lighthaus.nvim` setup:
```lua
require("lighthaus").setup({
	bg_dark = vim.env.SYS_THEME == "dark" and true or false,
	colors = {
		black = "#111111",
		fg_nc_statusline = "#888888",
	},
	lsp_underline_style = "undercurl",
})
-- maybe this command it's the cause ?
vim.cmd("highlight ColorColumn ctermbg=0 guibg=#111111")
```

On my config I have `vim.wo.colorcolumn = "80"` too.

version: `NVIM v0.7.0-dev`

**Comment by mrjones2014** [comment]
Sorry, I’m not sure what the actual issue is, could you clarify?

**Comment by marcelarie** [comment]
No problem. The issue is that the colorcolumn goes on top of some text.

here a recording:
![Peek 2022-03-01 12-20](https://user-images.githubusercontent.com/62728887/156160263-1a8b1818-dd52-40d9-b8be-f460afc34364.gif)

**Comment by marcelarie** [comment]
Thanks!!

**Comment by mrjones2014** [comment]
I think it's because I was setting the fg color instead of bg color for `ColorColumn` by mistake. @marcelarie could you update and let me know if it's fixed?

**Comment by mrjones2014** [comment]
you can also remove the `vim.cmd` line now, as it's redundant.

**Comment by marcelarie** [comment]
Yep now it's fixed!! Thanks!

**Comment by mrjones2014** [comment]
No problem, glad I could help!
