### ISSUE TITLE
Green color bg on Neo tree directory icons

### ISSUE THREAD

**Issue by hsheikhali1** [mrjones2014/lighthaus.nvim#14]
For some weird reason the theme is causing my directory items to have a green background and a black icon color for NeoTree
![Screen Shot 2022-05-19 at 3 18 36 PM](https://user-images.githubusercontent.com/14851850/169385830-0d74898c-3ae0-419c-91eb-0ae5ce51e184.png)

Any way to resolve this?

**Comment by hsheikhali1** [comment]
@mrjones2014 https://github.com/nvim-neo-tree/neo-tree.nvim/blob/v2.x/lua/neo-tree/ui/highlights.lua this might help

**Comment by mrjones2014** [comment]
Probably `NeoTreeDirectoryIcon`

**Comment by hsheikhali1** [comment]
Nice! it's fixed now!

![Screen Shot 2022-05-19 at 3 45 01 PM](https://user-images.githubusercontent.com/14851850/169389806-6ca89054-a0fa-474a-9b0e-4f4abdc64b5a.png)

**Comment by mrjones2014** [comment]
Fixed by 95a874f0f0b45fb775612f66eed30e4220d05cf5 and e3fc0593c37a54eab3f7743001bd491200786124
