### ISSUE TITLE
Missing cursorline highlight?

### ISSUE THREAD

**Issue by metalelf0** [mrjones2014/lighthaus.nvim#5]
Hey! Great work with the theme, I like it :) I'd just consider adding an highlight for the cursorline, as there is none at the moment.

Keep up the great work!

**Comment by marcelarie** [comment]
Hi, the cursorline is still missing in the dark variant. :)

**Comment by marcelarie** [comment]
Hi @mrjones2014, I use the dark variant of the theme with the cursorline. I think the color will look better being a darker shade of gray. If you already take it into consideration I override it, but it seems the same color of the lighter variant. 

![2022-02-16_08-13](https://user-images.githubusercontent.com/62728887/154214685-c96e670e-6995-40c3-bde9-7c9098a22fc2.png)

**Comment by marcelarie** [comment]
btw thanks for the theme. it's really cool :")

**Comment by mrjones2014** [comment]
Both of those colors have extremely low contrast with the background color, so I don't think they should be the defaults.

I'm open to tweaking the Lualine theme, but can you open a separate issue for that?


>btw thanks for the theme. it's really cool :")

thanks!
